baseURL = 'https://reproductiverights.wiki/'
languageCode = 'en-us'
title = 'Reproductive Rights'
theme = 'hextra'

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
site_logo = ""
description = "While Roe v. Wade was overturned, abortion remains legal in many states, and other reproductive health care services remain protected by law."

[[menu.main]]
name = "Your Rights"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Emergency Care"
pageRef = "/emergency-care"
weight = 2

[[menu.main]]
name = "Contact"
pageRef = "/contact"
weight = 3

